baseURL = "https://startup.monachelle.org"
googleAnalytics = ""
theme = "omega"
title = "Startup Monachelle"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "mission"
name = "About"
pre = "#"
weight = 1
[[menu.main]]
URL = "products"
name = "Projects"
pre = "#"
weight = 2
[[menu.main]]
URL = "career"
name = "Contribute"
pre = ""
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
pre = "#"
weight = 4
[params]
author = "Comunità Monachelle"
contact_info = "Via Raimondo Annecchino, 123M<br>Pozzuoli, NA<br>80078 ITALIA"
description = "Progetto di riqualificazione di Monachelle Bene Comune a Pozzuoli"
logo = "images/logo_monachelle.png"
logo_width = "100px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
[[params.social]]
icon = "fa-facebook"
link = "https://www.facebook.com/comitatoexconvittoMONACHELLE"
title = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/exmonachelle"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "https://www.instagram.com/exmonachelle/"
title = "instagram"
